[http]
bad_request = 400
unauthorized = 401
not_found = 404
internal = 500

[db]
connection = 1000
read = 1000
write = 1001
delete = 1002

[user]
password_wrong = 2001
password_invalid = 2002
not_found = 2003
update = 2004
password_token_invalid = 2005
  [duplicate]
  email = 2010
  username = 2011

[role]
duplicate = 4000
not_found = 4001
insufficient = 4002
