DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE "user" (
  id SERIAL,
  email VARCHAR(254) NOT NULL,
  username VARCHAR(30) NOT NULL,
  password CHAR(60),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (username),
  UNIQUE (email)
);

CREATE TABLE password_token (
  user_id INTEGER NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  token UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id),
  UNIQUE (token)
);

CREATE TABLE user_role (
  user_id INTEGER NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  role SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id)
);

CREATE TABLE deck (
  id SERIAL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE card (
  id SERIAL,
  "text" TEXT NOT NULL,
  "type" SMALLINT NOT NULL DEFAULT 0,
  deck_id INTEGER NOT NULL REFERENCES deck (id) ON DELETE RESTRICT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE lobby (
  id SERIAL,
  name TEXT NOT NULL,
  deck_id INTEGER NOT NULL REFERENCES deck (id) ON DELETE RESTRICT,
  size INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE participant (
  lobby_id INTEGER NOT NULL REFERENCES lobby (id) ON DELETE RESTRICT,
  user_id INTEGER NOT NULL REFERENCES "user" (id) ON DELETE RESTRICT,
  admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE result (
  lobby_id INTEGER NOT NULL REFERENCES lobby (id) ON DELETE RESTRICT,
  user_id INTEGER NOT NULL REFERENCES "user" (id) ON DELETE RESTRICT,
  points SMALLINT NOT NULL DEFAULT 0,
  joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (lobby_id, user_id)
);

CREATE TABLE round (
  lobby_id INTEGER NOT NULL REFERENCES lobby (id) ON DELETE RESTRICT,
  user_id INTEGER NOT NULL REFERENCES "user" (id) ON DELETE RESTRICT,
  round SMALLINT NOT NULL,
  card_id INTEGER NOT NULL REFERENCES card (id) ON DELETE RESTRICT,
  czar BOOLEAN NOT NULL DEFAULT FALSE,
  points SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (lobby_id, user_id, round)
);
